platform:ios, ‘8.0’

inhibit_all_warnings!
use_frameworks!

pod 'Alamofire', '~> 3.2.1'
pod 'SnapKit', '~> 0.19.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'SVProgressHUD', '~> 2.0-beta8'
pod 'AFNetworking', '~> 3.0.4'
